
volumes:
    db:
        driver: local

services:
    postgres:
        image: "postgres:latest"
        container_name: postgres
        restart: on-failure
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
            interval: 5s
            retries: 5

    migrations:
        image: "postgres:latest"
        container_name: migrations
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./sql:/migrations
        command: >
            sh -c "psql -U myuser -d mydatabase -f /migrations/initialise_data.sql"
        environment:
            PGPASSWORD: mypassword
            PGUSER: myuser
            PGDATABASE: mydatabase
            PGHOST: postgres
        restart: "no"

    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app
        restart: on-failure
        env_file:
            - .env
        environment:
            APPLICATION_PORT: 8080
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
            migrations:
                condition: service_completed_successfully